eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true

yandex:
  url: https://yandex.cloud/api/speechkit/tts